version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: "npm"
    directory: "/packages/typescript"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns: ["*"]
  - package-ecosystem: "pip"
    directory: "/packages/python"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns: ["*"]
